name: Deploy Flask Docker App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }} << EOF
          sudo apt update
          sudo apt install docker.io -y
          sudo systemctl start docker

          # DockerHub login
          echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Remove old container if exists
          sudo docker rm -f flask-app || true
          
          # Pull the latest image from DockerHub
          sudo docker pull atique123/flask-app:latest
          
          # Run the container
          sudo docker run -d -p 80:5000 --name flask-app atique123/flask-app:latest
        EOF
